steps:
  - name: "gcr.io/cloud-builders/docker"
    script: |
      docker build -t australia-southeast1-docker.pkg.dev/$PROJECT_ID/express-api/express-api:latest .
    automapSubstitutions: true
images:
  - "australia-southeast1-docker.pkg.dev/$PROJECT_ID/express-api/express-api:latest"
